name: Docker Image CI

on:
  workflow_dispatch:
      inputs:
        logLevel:
          description: 'Log level'
          required: true
          default: 'warning'
          type: choice
          options:
          - info
          - warning
          - debug
        tags:
          description: 'Test scenario tags'
          required: false
          type: boolean
        environment:
          description: 'Environment to run tests against'
          type: environment
          required: true
  push:
    branches: [ "docker-container" ]
  pull_request:
    branches: [ "docker-container" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file docker/app.dockerfile --tag namlim/crm-app-docker:$(date +%s)
